services:
  activemq:
    image: rmohr/activemq
    ports:
      - "8161:8161"
      - "61616:61616"
    networks:
      - dominet
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
  mysqldb:
    image: mysql:latest
    restart: always
    healthcheck:
      test: "test -f /tmp/init-done"
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
      start_interval: 30s
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    networks:
      - dominet
  domibus:
    image: local-docker/domibus
    container_name: domibus
    volumes:
      - ./conf/domibus/:/usr/local/tomcat/conf/domibus
    ports:
      - "8080:8080"
    networks:
      - dominet
    depends_on:
      mysqldb:
        condition: service_healthy
      activemq:
        condition: service_started
networks:
  dominet:
    driver: bridge